spring:
  application:
    name: hp
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}

server:
  port: 8998

idg:
  host: lb://idg
  genId:
    url: ${idg.host}/v0/id